### ISSUE TITLE
License

### ISSUE THREAD

**Issue by JirkaKrivanek** [leonbloy/pngj#50]
Let me apologise for stupid issue: I work for corporate and to satisfy their endless process, I need to know the license of this brick.

Something (and ideally) like "Apache 2"

**Comment by Lonzak** [comment]
Just check the license section in the pom.xml file:

https://github.com/leonbloy/pngj/blob/master/pom.xml

```
<licenses>
		<license>
			<name>The Apache Software License, Version 2.0</name>
			<url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
			<distribution>repo</distribution>
		</license>
</licenses>
```

**Comment by JirkaKrivanek** [comment]
Perfect thank you, and I am sorry, others typically mention this at the root github page...

**Comment by Lonzak** [comment]
You are welcome.
